### ISSUE TITLE
Master branch fails on fit where CRAN does not

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#153] opened 2020-07-15 04:07 UTC
This is a model that uses target stats directly (rather than ergm.ego), and fit via EpiModel `netest()` function.  It fits consistently with CRAN ergm, and mostly default controls (only MCMC.interval = 2e4).   MCMC diagnostics/GOF/simulations v. targets all look fine.

But fitting with ergm@master and the same controls almost always fails, and quickly.  Error message:

```
Error in ergm.MCMLE(init, nw, model, initialfit = (initialfit <- NULL),  : 
  Number of edges in a simulated network exceeds that in the observed by a factor of more than 20. This is a strong indicator of model degeneracy or a very poor starting parameter configuration. If you are reasonably certain that neither of these is the case, increase the MCMLE.density.guard control.ergm() parameter.
```

Upping SAN.maxit to 10 or 20 helps.  But I'm wondering why we need to do this now, and didn't need to before.

dump of the session attached for reprex.

model is:

```
netest_inst <- netest(
  nw_inst,
  formation = model_inst,
  target.stats = unname(targetstats_inst), # must be an unnamed numeric
  coef.diss = dissolution_coefs(~offset(edges), 1),
  set.control.ergm = control.ergm(
                       MCMC.interval = 2e4,
                       # SAN.maxit = 10,
                       # SAN.nsteps.times = 20,
                       parallel = np, parallel.type=ptype))
```

session info (most recent versions of master branches)

```
> sessioninfo::package_info(pkgs = c("network", "statnet.common",
+                                    "ergm", "tergm", "EpiModel"), 
+                           dependencies = FALSE)
 package        * version     date       lib source                                 
 EpiModel       * 2.0.0       2020-07-15 [1] Github (statnet/EpiModel@ac02e1b)      
 ergm           * 3.10.4-5582 2020-07-15 [1] Github (statnet/ergm@0ea962e)          
 network        * 1.17.0-413  2020-07-15 [1] Github (statnet/network@78caa79)       
 statnet.common   4.4.0-272   2020-07-15 [1] Github (statnet/statnet.common@dc49897)
 tergm          * 3.6.2-1955  2020-07-15 [1] Github (statnet/tergm@dd178d6)         
```

[ergm_dump.zip](https://github.com/statnet/ergm/files/4922837/ergm_dump.zip)

**Comment by chad-klumb** [comment] 2020-07-15 18:31
One difference between CRAN and master is the default number of dyads visited by the MPLE.  When initial fit is not final, the current default in master is `max(e, 40)*8` where `e` is the number of edges.  IMO this may be too low (I always increase it when fitting models myself).  You could try setting the `init.MPLE.samplesize` control argument to a large number (at least `1e6`) and see if that helps.

I wasn't able to actually reproduce your example because the `rda` file does not appear to include the network itself.  In particular, referencing it in the formula environment produces the error

```
Error: object 'nw_inst' not found
```

**Comment by martinamorris** [comment] 2020-07-15 20:26
Nice call @chad-klumb, using `init.MPLE.samplesize=1e6` it fit in 2 iterations with just the `MCMC.interval` modified -- estimation time dropped from 6 to 2 seconds, relative to increasing the SAN maxit.

Is it worth changing the default on `init.MPLE.samplesize`?  It's a pretty obscure parameter, and if there's a better way to set it adaptively to the analysis at hand, that would be great.

@Shmelder tagging you so you can follow this thread.

**Comment by martinamorris** [comment] 2020-07-15 20:28
and re: not being able to use the dump rda file, that's annoying.  i know i used this approach with Pavel a couple months back to dx a model that was failing, and i thought the nw on the LHS was saved in the formula environment.

**Comment by krivit** [comment] 2020-07-20 01:19
@martinamorris , I think the problem might be that `formula` grabs whatever environment it's been defined in, but if that environment happens to be `GlobalEnv` (R's default user workspace), then it doesn't grab its elements but rather the fact that it grabbed `GlobalEnv`. This means that making it fully reproducible might also involve saving the R workspace.

**Comment by krivit** [comment] 2020-09-04 07:00
@martinamorris , is this still a problem? Can you attach both the `ergm` dump and the workspace image (i.e., `save.image('globalEnv.rda')`)?

**Comment by chad-klumb** [comment] 2020-09-04 19:23
One thing to consider before pushing `master` to CRAN is the default `init.MPLE.samplesize`.  As mentioned above I almost always increase it.  It seems that the low default value may be responsible for sub-optimal results in some cases, and if this happens to a naive user, they may have a hard time figuring out what's going wrong.

I would personally be fine with combining `MPLE.samplesize` and `init.MPLE.samplesize` into a single argument (probably named `MPLE.samplesize`) and having the default be `.Machine$integer.max` (the current `MPLE.samplesize` default).  If we insist on keeping them as separate arguments, I'd be more comfortable with an `init.MPLE.samplesize` default of `100*edges` or `1000*edges` than the current `8*edges`.

Speaking for myself, the thought behind making the `MPLE` samplesize easier to control was that a sufficiently aware user running large networks would have an easier time getting predictable behavior (than with the previously available unique dyad types control).  I didn't imagine it as a way to shave a few seconds (or less) off small to medium network fits (unless the user was really intent on doing that manually, in which case it would be their responsibility to make sure it's working).

**Comment by martinamorris** [comment] 2020-09-04 19:54
what @chad-klumb said

**Comment by krivit** [comment] 2020-09-05 00:26
@chad-klumb , interesting. In principle, the a given MPLE sample size should give you almost same level of precision regardless of network size (for sufficiently large networks), so it's not clear why the default wouldn't be sufficient. In practice, I wonder if the systematic sampling we are using is actually doing what it's supposed to, and if not, why not.

**Comment by krivit** [comment] 2020-09-25 05:18
For the use case you described (600 edges, 15k nodes), the new default of `max(sqrt(d),e,40)*8` would take a systematic sample of about 85k dyads. How well does that work for the test case?

**Comment by krivit** [comment] 2020-10-03 03:04
@martinamorris , @chad-klumb , I am hoping to submit `ergm` next week. Can you confirm whether the new default fixes the problem?

**Comment by chad-klumb** [comment] 2020-10-06 02:08
I will rerun the cohab model tomorrow with the new defaults and see if it now works consistently.

**Comment by chad-klumb** [comment] 2020-10-06 18:48
Performance was adequate in all of 22 runs tested.  On average it seems to be slower overall (due to additional MCMC iterations) than with `init.MPLE.samplesize` set manually to a larger value, but it's nothing to hold up the release for.

**Comment by krivit** [comment] 2020-10-07 11:37
OK. One day, we may consider some adaptive algorithm, but for now, I am going to close this and see if I can start the release process.

**Closed** 2020-10-13 02:33 UTC
Labels: Component: Estimation, Language: R, Type: Bug, bug
