### ISSUE TITLE
ergm estimation fails with simple EpiModel netsim call (was: simulate.stergm fails)

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#156] opened 2020-07-25 19:28 UTC
This started with an email from a user (Tom Kraft), who was working with CRAN versions of all packages.  As I tried to track it down I found this other issue.  Note, he's using `EpiModel`, but it seems like this problem only arises when CRAN `EpiModel` is used with the release candidates of the `statnet` packages (public@master), which points to something having changed in the `statnet` packages.

This code works with CRAN versions:
```
library(EpiModel)
nw1 <- network.initialize(n = 90, directed=F)
nw1 %v% "com2" <- c(rep(as.character(c(1:9)), each=10 ))
fit1 <- netest(nw1, formation = ~edges + nodematch("com2") , 
               target.stats = c(200,  200), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                     duration = c(25)))
sim1 <- simulate(fit1$fit)
```

But it generates this error with CRAN `EpiModel` + release candidates of the statnet packages:

```
> sim1 <- simulate(fit1$fit)
Error in get(name, pos = environment(new)) : 
  argument "set.control.stergm" is missing, with no default
```

I recall that @chad-klumb was going to make some updates to allow `control.stergm` parameters to be passed in `EpiModel` , but I don't see any pull requests on `EpiModel` from Chad.  So I'll just leave it here.

versions:
```
> sessioninfo::package_info(pkgs = c("network", "networkDynamic", "statnet.common",
+                                    "ergm", "tergm", "EpiModel"), 
+                                    dependencies = FALSE)
 package        * version    date       lib source                                 
 EpiModel       * 1.8.0      2020-05-08 [2] CRAN (R 4.0.2)                         
 ergm           * 4.0-5594   2020-07-25 [1] Github (statnet/ergm-private@62d66be)  
 network        * 1.17.0-413 2020-07-23 [1] Github (statnet/network@78caa79)       
 networkDynamic * 0.10.1     2020-07-18 [1] Github (statnet/networkDynamic@157dede)
 statnet.common   4.4.0-273  2020-07-23 [1] Github (statnet/statnet.common@8bc8c58)
 tergm          * 3.6.2-1955 2020-07-18 [1] Github (statnet/tergm@dd178d6)         

[1] C:/Users/Martina Morris/Documents/R/release-library
[2] C:/Users/Martina Morris/Documents/R/win-library/4.0
[3] C:/Program Files/R/R-4.0.2/library
```

**Comment by martinamorris** [comment] 2020-07-26 20:15
Thanks for noticing that @chad-klumb.  That was the result of a mis-placed install.

I've moved this over to the `ergm` repo, as I think the OP's issue belongs here, even though he's using EpiModel.

Tom Kraft reported on errors running the code below.  The smaller network case runs, the scaled up case does not.  His example has all ties on the diagonal of a 2 level factor.  I've pasted his code in, along with the fixes I explored.

But I'm wondering if the problem is that  pure homophily makes the edges and nodematch terms co-linear (they're identical).  If so, why does the model for the smaller net work? @krivit 


```
# Works
nw1 <- network.initialize(n = 90, directed=F)
nw1 %v% "com2" <- c(rep(as.character(c(1:9)), each=10 ))
fit1 <- netest(nw1, formation = ~edges + nodematch("com2") , 
               target.stats = c(200, 200), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                     duration = 25))
summary(fit1)
dx1 <- netdx(fit1, nsims = 2, nsteps = 200)
dx1


# Fails
nw2 <- network.initialize(n = 9000, directed=F)
nw2 %v% "com2" <- c(rep(as.character(c(1:900)), each=10 ))
fit2 <- netest(nw2, formation = ~edges + nodematch("com2") , 
               target.stats = c(20000, 20000), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                             duration = 25))
dx2 <- netdx(fit2, nsims = 2, nsteps = 200)
```
The error is either that MCMC estimation gets stuck, or it doesn't converge in 20 iter.

I've replicated his error with CRAN versions, and public@master versions.  I thought the problem might be that the larger net needs more SAN time, and a bigger MPLE samplesize to get better starting estimates, so tried tinkering with some of these controls (shown below with max values I tried).  No change.

```
nw2 <- network.initialize(n = 9000, directed=F)
nw2 %v% "com2" <- c(rep(as.character(c(1:900)), each=10 ))
fit2 <- netest(nw2, formation = ~edges + nodematch("com2") , 
               target.stats = c(20000, 20000), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                             duration = 25),
               set.control.ergm = control.ergm(MPLE.samplesize=1e6, # init.MPLE.samplesize if master
                                               MCMC.burnin = 1e6,
                                               MCMLE.iter = 100,
                                               SAN.maxit = 00,
                                               SAN.nsteps.times = 20))
dx2 <- netdx(fit2, nsims = 2, nsteps = 200)
```

**Comment by krivit** [comment] 2020-07-28 07:04
@martinamorris , the statistics are only collinear at the MLE, not in general, but it is a symptom of the problem. The cause is, as you say, that no non-homophilous ties are possible for the target statistics.

This means that the target statistics are on the boundary of the convex hull of possible statistics, as opposed to its interior. Therefore, the MLE is infinite, and it's not even the kind of infinite that we can detect and "drop": the MLE is something like

<img src="https://render.githubusercontent.com/render/math?math=\displaystyle \lim_{x\to +\infty} (-x, x %2B q)"/>

where *q* is the log-odds of a tie given that the dyad is homophilous. The reason it converges at all is that with enough computational investment, it can get to a point in that limit where the distribution of networks induced by the parameters is indistinguishable from that under this infinite MLE.

Running
```r
nw2 <- network.initialize(n = 9000, directed=F)
nw2 %v% "com2" <- c(rep(as.character(c(1:900)), each=10 ))
fit2 <- netest(nw2, formation = ~edges + nodematch("com2") , 
               target.stats = c(20000, 20000), 
               coef.diss = dissolution_coefs(dissolution = ~offset(edges), 
                                             duration = 25),
               set.control.ergm = control.ergm(MPLE.samplesize=1e6, # init.MPLE.samplesize if master
                                               MCMC.burnin = 1e6,
                                               MCMC.interval = 1e5,
                                               MCMLE.maxit = 100,
                                               SAN.maxit = 10,
                                               SAN.nsteps.times = 40), verbose=TRUE)
```
converged (for my random seed, whatever it was) in 62 iterations. In the last several, it threw several collinearity warnings:
```
Warning: Model statistics ‘nodematch.com2’ are linear combinations of some set of preceding statistics at the current stage of the estimation. This may indicate that the model is nonidentifiable.
```

Also, in your code example, `SAN.maxit` is set to 0 and `MCMLE.iter` should be `MCMLE.maxit`.

**Comment by martinamorris** [comment] 2020-07-30 23:14
thx @krivit .  i guess what i meant was that the statistics are collinear by definition.  but the point is that they're on the boundary.

checking the estimates from the smaller net, which stops at the MPLE, they are: (-21.88, 21.86)

for off-diag ties, then, the p(tie) = expit(theta(edges)) = 2.85

that doesn't make sense as a probability.

**Comment by krivit** [comment] 2020-07-31 01:24
@martinamorris , it is mathematically impossible for the expit function to return a value that is not between 0 and 1. What this estimate predicts is

* p(tie | nonhomophilous) = expit(-21.88) ≈ 0;

* p(tie | homophilous) = expit(-21.88 + 21.86) = expit(-0.02) = 0.495.

**Comment by martinamorris** [comment] 2020-07-31 01:28
ok, mebbe i'm just zonked:  

> exp(-21.88/(1+(-21.88)))
[1] 2.851636

**Comment by krivit** [comment] 2020-07-31 01:52
Um, exponentiation is the first thing you do, not the last:
```r
expit <- function(x) exp(x)/(1+exp(x))
```
Though, there might be alternative implementations that are more numerically stable.

**Comment by martinamorris** [comment] 2020-07-31 16:28
right...  a testament to my state of mind.  thx.

**Comment by krivit** [comment] 2020-08-01 07:09
Since this looks like a problem with a bad model and statistics combination, is everyone OK with closing this ticket?

**Comment by martinamorris** [comment] 2020-08-01 17:24
yes.

**Comment by krivit** [comment] 2020-08-01 23:19
I probably should have asked "Is anyone *not* OK with closing this?", but I will assume that Martina is speaking on everyone's behalf. :-)

**Closed by krivit** 2020-08-01 23:19 UTC
