### ISSUE TITLE
concerning results from weighted SAN

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#117] opened 2019-08-23 00:04 UTC
In trying to write tests for the weighted SAN updates I came across some concerning behavior.  I have relatively little experience with the weighted side of things, so I might be misunderstanding something here, but I thought the results were curious enough to be worth posting here for discussion.

It appears weighted SAN has extreme difficulty fitting `edges + sum` target stats.  Here is some output (technically from `dev` but similar behavior was observed with CRAN):

```
> require(ergm)
> 
> x <- network(50, directed=FALSE, numedges=0)
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san())
> summary(y ~ edges + sum, response="ea")
 nonzero      sum 
 537.000 2636.764 
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san(SAN.nsteps=1e6))
> summary(y ~ edges + sum, response="ea")
 nonzero      sum 
 266.000 1105.919 
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san(SAN.nsteps=1e7))
> summary(y ~ edges + sum, response="ea")
nonzero     sum 
 262.00 1074.15 
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san(SAN.nsteps=1e8))
> summary(y ~ edges + sum, response="ea")
 nonzero      sum 
218.0000 879.9321 
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san(SAN.nsteps=1e9))
> summary(y ~ edges + sum, response="ea")
 nonzero      sum 
216.0000 863.1478 
> 
> y <- san(x ~ edges + sum, reference=~Unif(0,10),target.stats=c(200, 800),response="ea",control=control.san(SAN.nsteps=2e9))
> summary(y ~ edges + sum, response="ea")
 nonzero      sum 
218.0000 874.0272 
```

Edited to add: longer intervals; if it's converging to the target stats, it's doing so *extremely* slowly

Even for an extremely large number of steps, SAN results appear to be unnecessarily bad: deleting *any* edge from the final network would necessarily improve the target stat match, and the final iteration should have been quite long, so why didn't it delete those edges?

Such problems did not appear with only `edges` or only `sum`; the combination `edges + sum` was needed to generate this behavior.

The proposal used (not explicitly specified) was `DistRLE` (which I don't know anything about).

Am I misunderstanding or misusing weighted SAN, or are these results indicative of a problem?

**Comment by martinamorris** [comment] 2019-08-24 01:50
... taking the liberty to assign this to Pavel.

**Comment by krivit** [comment] 2019-08-25 04:56
At first, I thought it was a problem with an inefficient proposal. On further thought, the problem is deeper than that, going all the way to measure theory.

Uniform(0,10) is a continuous distribution. Therefore, the probability of any specific value---including 0---is 0, and no finite `edges` effect can change that. If you simulated from this model with any finite coefficients, you would get, after burnin, a network with no non-edges and a distribution governed only by the coefficient on `sum`.

From the point of view of MCMC, this means that there will almost never (i.e., with probability 0) be a proposal to set any dyad to exactly 0, so there will never be an opportunity to increase the `edges` coefficient, only opportunities to decrease it.

Now, since the network starts out as a network of 0s, `san` can actually get to where it needs to go, but once it overshoots and has more than 200 nonzeros, it can never bring it back down. The thing that puzzles me here is why using more iterations results in getting closer rather than farther away. The statistics scaling for the shorter runs gives slightly more weight to `sum` than longer runs do, which would explain it, I guess, but I don't know why it does that.

**Comment by krivit** [comment] 2019-08-26 02:04
The puzzle aside, this might be "working as intended": you can't expect MCMC to find configurations that have probability 0 under the reference distribution. We may want to implement support for mixture reference distributions in the future. This might be doable by alternating MH proposals for different distributions.

**Comment by chad-klumb** [comment] 2019-08-26 02:25
Interesting; I guess I assumed that toggling an edge "off" was a possibility, regardless of the reference distribution, but it sounds like that would really require a point mass at zero (which makes sense).

**Comment by krivit** [comment] 2019-08-28 02:38
Good question. It *is* getting better slowly, but it should be getting better much faster.

**Comment by krivit** [comment] 2020-09-20 12:23
On further thought, it shouldn't necessarily decrease it that much faster, because the probability of making a proposal that decreases the value of a given dyad is proportional to the current value of that dyad. E.g., for a `Unif(0,10), if the starting dyad value is 5, then there is a 50% chance, but if it's already at 1, then there is only a 10% chance; so there are diminishing returns.

It might be worth considering a TNT analogue that first makes a decision whether to increase or decrease a value, then samples within the range. But, for now, it's really not a bug.

**Closed by krivit** 2020-09-20 12:23 UTC
Labels: Type: Question, invalid, question
