### ISSUE TITLE
Issue using ergm() with new packages

### ISSUE THREAD

**Issue by jrstew** [statnet/ergm#254] opened 2021-03-30 15:43 UTC
Running 

data(sampson)
ergm(samplike ~ edges)

results in error 

Error: 'function' is not a function, but of type 8

I would note that ergm is in the namespace of the session. 

I recently downloaded master versions of statnet.common, network, and ergm and installed. I have copied my session info below in case there is some versioning issue with R or another package. 

Session info: 

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ergm_4.0-6118      network_1.17.0-666

loaded via a namespace (and not attached):
 [1] lpSolveAPI_5.5.2.0-17.7  magrittr_1.5             MASS_7.3-53
 [4] tidyselect_1.1.0         lattice_0.20-41          R6_2.4.1
 [7] rlang_0.4.6              dplyr_1.0.0              tools_4.0.3
[10] parallel_4.0.3           grid_4.0.3               rle_0.9.2
[13] coda_0.19-3              ellipsis_0.3.1           digest_0.6.25
[16] tibble_3.0.1             lifecycle_0.2.0          crayon_1.3.4
[19] Matrix_1.2-18            purrr_0.3.4              vctrs_0.3.1
[22] trust_0.1-8              memoise_1.1.0            glue_1.4.1
[25] robustbase_0.93-6        statnet.common_4.5.0-340 DEoptimR_1.0-8
[28] compiler_4.0.3           pillar_1.4.4             generics_0.1.0
[31] pkgconfig_2.0.3

**Comment by jrstew** [comment] 2021-03-30 19:45
>Can you try running ... to make absolutely certain that the version matches the latest on GitHub?

I ran these and re-installed the packages and the same issue occurs in a clean R session. 

Is it possible that this is due to the R version? I am on R version 4.0.3 (2020-10-10) but the current is 4.0.4. It would be surprising if that were the issue, as it is only one off, but maybe? 


To note, the CRAN versions work fine. I installed and compiled the source from CRAN and in a new clean R session, ran the command and no errors and regular behavior.

**Comment by krivit** [comment] 2021-03-30 20:14
It could be the R version, though highly unlikely.

What does the traceback show?

Also, can you try updating the other packages? For example, your version of `memoise` is 1.1.0, while the version on CRAN is 2.0.0.

**Comment by krivit** [comment] 2021-04-02 02:57
Since there is no clear path to reproducing this, I am closing this issue. When/If you have more information, please reopen.

**Comment by jrstew** [comment] 2021-04-02 14:41
Wanted to update confirming the issue is closed: 

Doing an install of all updated packages and dependencies has solved the issue. 

Unfortunately, all were installed at the same time so I am not sure what was the offending package. But wanted to comment for helpfulness that there is something that is not back-compatible in the pipeline.

**Comment by martinamorris** [comment] 2021-04-02 16:40
@krivit since we're testing a huge overhaul of the suite, i don't think it's a good idea to close this.

@jrstew what OS are you using -- perhaps we could see that's part of the issue.

**Comment by martinamorris** [comment] 2021-04-02 16:48
ah, ok just saw @jrstew's closing comment.  i'm not surprised that there are some backwards incompatibilities -- we did not enforce that (nor can we, i think, given the size of our operation).

**Closed by martinamorris** 2021-04-02 16:48 UTC

**Comment by jrstew** [comment] 2021-04-02 16:54
@martinamorris  I am on Mac OS version 11.2.3 just to put the information here. 

I agree about the challenge involved in ensuring backwards compatibility with many dependencies. It might be good to suggest for people to update all dependencies when this is released to CRAN if others experience this issue.
