### ISSUE TITLE
when i add same nodes  distance and language Exogenous contextual network, I meet some problem

### ISSUE THREAD

**Issue by ru-zheng** [statnet/ergm#446] opened 2022-04-06 13:46 UTC
when i add  distance and language Exogenous contextual network(from CEPII dataset) which with the same nodes with origin trade network, I meet some problem:
Error in if (any(low.drop.theta)) message(paste("Observed statistic(s)",  : missing value where TRUE/FALSE needed

I did not know how to do,maybe I can construct  distance network and language network with all given nodes?

**Comment by krivit** [comment] 2022-04-10 11:16
Thank you for the report! Could you please provide a reproducible example?

**Comment by krivit** [comment] 2023-01-18 03:15
No reply since April. I'm closing this until there is a reproducible example.

**Closed by krivit** 2023-01-18 03:15 UTC
